/*
 * Wordle - a self-contained offline 5-letter word guessing game.
 *
 * RULES
 *   The hidden word is a 5-letter word chosen from the answer pool.
 *   You get 6 guesses. After each guess every letter is coloured:
 *     green  - letter is correct and in the right spot
 *     yellow - letter is in the word but in the wrong spot
 *     gray   - letter is not in the word
 *
 * CONTROLS
 *   Touch / Mouse : tap the on-screen keys, or the New Word / restart
 *                   button in the header.
 *   Keyboard      : A-Z type a letter, Backspace deletes, Enter submits,
 *                   R or the header button restarts.
 *
 * SHARE
 *   After the game the emoji board is shown in the result panel and can
 *   be copied to the clipboard ("Copy results") with a fallback that
 *   works even when the Clipboard API is unavailable.
 *
 * WORD LIST
 *   The dictionary (all valid guesses) and the answer pool are embedded
 *   below. Both were derived from the repository's `_words.txt` during
 *   development.
 *
 * PERSISTENCE
 *   Win/loss stats are kept in localStorage under "wordle_stats".
 */
(function () {
  "use strict";

var DICT = [
  "aaron",
  "about",
  "above",
  "abuse",
  "acids",
  "acres",
  "actor",
  "acute",
  "adams",
  "added",
  "admin",
  "admit",
  "adobe",
  "adopt",
  "adult",
  "after",
  "again",
  "agent",
  "aging",
  "agree",
  "ahead",
  "aimed",
  "alarm",
  "album",
  "alert",
  "alias",
  "alice",
  "alien",
  "align",
  "alike",
  "alive",
  "allah",
  "allan",
  "allen",
  "allow",
  "alloy",
  "alone",
  "along",
  "alpha",
  "alter",
  "amber",
  "amend",
  "amino",
  "among",
  "angel",
  "anger",
  "angle",
  "angry",
  "anime",
  "annex",
  "annie",
  "apart",
  "apnic",
  "apple",
  "apply",
  "april",
  "arbor",
  "areas",
  "arena",
  "argue",
  "arise",
  "armed",
  "armor",
  "array",
  "arrow",
  "aruba",
  "ascii",
  "asian",
  "aside",
  "asked",
  "asset",
  "atlas",
  "audio",
  "audit",
  "autos",
  "avoid",
  "award",
  "aware",
  "awful",
  "babes",
  "bacon",
  "badge",
  "badly",
  "baker",
  "bands",
  "banks",
  "barry",
  "based",
  "bases",
  "basic",
  "basin",
  "basis",
  "batch",
  "baths",
  "beach",
  "beads",
  "beans",
  "bears",
  "beast",
  "beats",
  "began",
  "begin",
  "begun",
  "being",
  "belle",
  "belly",
  "below",
  "belts",
  "bench",
  "berry",
  "betty",
  "bible",
  "bikes",
  "bills",
  "billy",
  "bingo",
  "birds",
  "birth",
  "black",
  "blade",
  "blair",
  "blake",
  "blame",
  "blank",
  "blast",
  "blend",
  "bless",
  "blind",
  "blink",
  "block",
  "blogs",
  "blond",
  "blood",
  "bloom",
  "blues",
  "board",
  "boats",
  "bobby",
  "bonds",
  "bones",
  "bonus",
  "books",
  "boost",
  "booth",
  "boots",
  "booty",
  "bored",
  "bound",
  "boxed",
  "boxes",
  "brain",
  "brake",
  "brand",
  "brass",
  "brave",
  "bread",
  "break",
  "breed",
  "brian",
  "brick",
  "bride",
  "brief",
  "bring",
  "broad",
  "broke",
  "brook",
  "brown",
  "bruce",
  "brush",
  "bryan",
  "bucks",
  "buddy",
  "build",
  "built",
  "bunch",
  "bunny",
  "burke",
  "burns",
  "burst",
  "buses",
  "butts",
  "buyer",
  "bytes",
  "cabin",
  "cable",
  "cache",
  "cakes",
  "calls",
  "camel",
  "camps",
  "canal",
  "candy",
  "canon",
  "cards",
  "carey",
  "cargo",
  "carlo",
  "carol",
  "carry",
  "cases",
  "casey",
  "casio",
  "catch",
  "cause",
  "cedar",
  "cells",
  "cents",
  "chain",
  "chair",
  "chaos",
  "charm",
  "chart",
  "chase",
  "cheap",
  "cheat",
  "check",
  "chess",
  "chest",
  "chevy",
  "chick",
  "chief",
  "child",
  "chile",
  "china",
  "chips",
  "choir",
  "chose",
  "chris",
  "chuck",
  "cindy",
  "cisco",
  "cited",
  "civic",
  "civil",
  "claim",
  "clara",
  "clark",
  "class",
  "clean",
  "clear",
  "clerk",
  "click",
  "cliff",
  "climb",
  "clips",
  "clock",
  "clone",
  "close",
  "cloth",
  "cloud",
  "clubs",
  "coach",
  "coast",
  "codes",
  "cohen",
  "coins",
  "colin",
  "colon",
  "color",
  "combo",
  "comes",
  "comic",
  "condo",
  "congo",
  "const",
  "coral",
  "corps",
  "costa",
  "costs",
  "could",
  "count",
  "court",
  "cover",
  "crack",
  "craft",
  "craig",
  "craps",
  "crash",
  "crazy",
  "cream",
  "creek",
  "crest",
  "crime",
  "crops",
  "cross",
  "crowd",
  "crown",
  "crude",
  "cubic",
  "curve",
  "cyber",
  "cycle",
  "czech",
  "daddy",
  "daily",
  "dairy",
  "daisy",
  "dance",
  "danny",
  "dated",
  "dates",
  "david",
  "davis",
  "deals",
  "dealt",
  "death",
  "debug",
  "debut",
  "decor",
  "delay",
  "delhi",
  "delta",
  "dense",
  "depot",
  "depth",
  "derby",
  "derek",
  "devel",
  "devil",
  "devon",
  "diana",
  "diane",
  "diary",
  "dicke",
  "diego",
  "diffs",
  "digit",
  "dirty",
  "disco",
  "discs",
  "disks",
  "dodge",
  "doing",
  "dolls",
  "donna",
  "donor",
  "doors",
  "doubt",
  "dover",
  "dozen",
  "draft",
  "drain",
  "drama",
  "drawn",
  "draws",
  "dream",
  "dress",
  "dried",
  "drill",
  "drink",
  "drive",
  "drops",
  "drove",
  "drugs",
  "drums",
  "drunk",
  "dryer",
  "dubai",
  "dutch",
  "dying",
  "dylan",
  "eagle",
  "early",
  "earth",
  "ebony",
  "ebook",
  "eddie",
  "edgar",
  "edges",
  "egypt",
  "eight",
  "elder",
  "elect",
  "elite",
  "ellen",
  "ellis",
  "elvis",
  "emacs",
  "email",
  "emily",
  "empty",
  "ended",
  "endif",
  "enemy",
  "enjoy",
  "enter",
  "entry",
  "epson",
  "equal",
  "error",
  "essay",
  "essex",
  "euros",
  "evans",
  "event",
  "every",
  "exact",
  "exams",
  "excel",
  "exist",
  "extra",
  "faced",
  "faces",
  "facts",
  "fails",
  "fairy",
  "faith",
  "falls",
  "false",
  "fancy",
  "fares",
  "farms",
  "fatal",
  "fatty",
  "fault",
  "favor",
  "fears",
  "feeds",
  "feels",
  "fence",
  "ferry",
  "fever",
  "fewer",
  "fiber",
  "fibre",
  "field",
  "fifth",
  "fifty",
  "fight",
  "filed",
  "files",
  "filme",
  "films",
  "final",
  "finds",
  "fired",
  "fires",
  "firms",
  "first",
  "fixed",
  "fixes",
  "flags",
  "flame",
  "flash",
  "fleet",
  "flesh",
  "float",
  "flood",
  "floor",
  "flour",
  "flows",
  "floyd",
  "fluid",
  "flush",
  "flyer",
  "focal",
  "focus",
  "folks",
  "fonts",
  "foods",
  "force",
  "forge",
  "forms",
  "forth",
  "forty",
  "forum",
  "fotos",
  "found",
  "frame",
  "frank",
  "fraud",
  "fresh",
  "front",
  "frost",
  "fruit",
  "fully",
  "funds",
  "funky",
  "funny",
  "fuzzy",
  "gains",
  "games",
  "gamma",
  "gates",
  "gauge",
  "genes",
  "genre",
  "ghana",
  "ghost",
  "giant",
  "gifts",
  "girls",
  "given",
  "gives",
  "glass",
  "glenn",
  "globe",
  "glory",
  "gnome",
  "goals",
  "going",
  "gonna",
  "goods",
  "gotta",
  "grace",
  "grade",
  "grain",
  "grams",
  "grand",
  "grant",
  "graph",
  "grass",
  "grave",
  "great",
  "greek",
  "green",
  "grill",
  "gross",
  "group",
  "grove",
  "grown",
  "grows",
  "guard",
  "guess",
  "guest",
  "guide",
  "guild",
  "hairy",
  "haiti",
  "hands",
  "handy",
  "happy",
  "harry",
  "haven",
  "hayes",
  "heads",
  "heard",
  "heart",
  "heath",
  "heavy",
  "helen",
  "hello",
  "helps",
  "hence",
  "henry",
  "herbs",
  "highs",
  "hills",
  "hindu",
  "hints",
  "hired",
  "hobby",
  "holds",
  "holes",
  "holly",
  "homes",
  "honda",
  "honey",
  "honor",
  "hoped",
  "hopes",
  "horse",
  "hosts",
  "hotel",
  "hours",
  "house",
  "howto",
  "human",
  "humor",
  "icons",
  "idaho",
  "ideal",
  "ideas",
  "image",
  "inbox",
  "index",
  "india",
  "indie",
  "inner",
  "input",
  "intel",
  "inter",
  "intro",
  "iraqi",
  "irish",
  "isaac",
  "islam",
  "issue",
  "italy",
  "items",
  "ivory",
  "jacob",
  "james",
  "jamie",
  "janet",
  "japan",
  "jason",
  "jeans",
  "jenny",
  "jerry",
  "jesse",
  "jesus",
  "jewel",
  "jimmy",
  "johns",
  "joins",
  "joint",
  "jokes",
  "jones",
  "joyce",
  "judge",
  "juice",
  "julia",
  "julie",
  "karen",
  "karma",
  "kathy",
  "katie",
  "keeps",
  "keith",
  "kelly",
  "kenny",
  "kenya",
  "kerry",
  "kevin",
  "kills",
  "kinda",
  "kinds",
  "kings",
  "kitty",
  "klein",
  "knife",
  "knock",
  "known",
  "knows",
  "kodak",
  "korea",
  "label",
  "labor",
  "laden",
  "lakes",
  "lamps",
  "lance",
  "lands",
  "lanes",
  "lanka",
  "large",
  "larry",
  "laser",
  "later",
  "latex",
  "latin",
  "laugh",
  "laura",
  "layer",
  "leads",
  "learn",
  "lease",
  "least",
  "leave",
  "leeds",
  "legal",
  "lemon",
  "leone",
  "level",
  "lewis",
  "lexus",
  "light",
  "liked",
  "likes",
  "limit",
  "linda",
  "lined",
  "lines",
  "links",
  "linux",
  "lions",
  "lists",
  "lived",
  "liver",
  "lives",
  "lloyd",
  "loads",
  "loans",
  "lobby",
  "local",
  "locks",
  "lodge",
  "logan",
  "logic",
  "login",
  "logos",
  "looks",
  "loops",
  "loose",
  "lopez",
  "lotus",
  "louis",
  "loved",
  "lover",
  "loves",
  "lower",
  "lucas",
  "lucia",
  "lucky",
  "lunch",
  "lycos",
  "lying",
  "lyric",
  "macro",
  "magic",
  "mails",
  "maine",
  "major",
  "maker",
  "makes",
  "males",
  "malta",
  "mambo",
  "manga",
  "manor",
  "maple",
  "march",
  "marco",
  "mardi",
  "maria",
  "marie",
  "mario",
  "marks",
  "marsh",
  "mason",
  "match",
  "maybe",
  "mayor",
  "mazda",
  "meals",
  "means",
  "meant",
  "medal",
  "media",
  "meets",
  "menus",
  "mercy",
  "merge",
  "merit",
  "merry",
  "metal",
  "meter",
  "metro",
  "meyer",
  "miami",
  "micro",
  "might",
  "milan",
  "miles",
  "mills",
  "minds",
  "mines",
  "minor",
  "minus",
  "mixed",
  "mixer",
  "model",
  "modem",
  "modes",
  "money",
  "monte",
  "month",
  "moore",
  "moral",
  "moses",
  "motel",
  "motor",
  "mount",
  "mouse",
  "mouth",
  "moved",
  "moves",
  "movie",
  "mpegs",
  "msgid",
  "multi",
  "music",
  "myers",
  "mysql",
  "nails",
  "naked",
  "named",
  "names",
  "nancy",
  "nasty",
  "naval",
  "needs",
  "nepal",
  "nerve",
  "never",
  "newer",
  "newly",
  "niger",
  "night",
  "nikon",
  "noble",
  "nodes",
  "noise",
  "nokia",
  "north",
  "noted",
  "notes",
  "notre",
  "novel",
  "nurse",
  "nylon",
  "oasis",
  "occur",
  "ocean",
  "offer",
  "often",
  "older",
  "olive",
  "omaha",
  "omega",
  "onion",
  "opens",
  "opera",
  "orbit",
  "order",
  "organ",
  "oscar",
  "other",
  "ought",
  "outer",
  "owned",
  "owner",
  "oxide",
  "ozone",
  "packs",
  "pages",
  "paint",
  "pairs",
  "panel",
  "panic",
  "pants",
  "paper",
  "papua",
  "paris",
  "parks",
  "parts",
  "party",
  "pasta",
  "paste",
  "patch",
  "paths",
  "patio",
  "paxil",
  "peace",
  "pearl",
  "peers",
  "penny",
  "perry",
  "perth",
  "peter",
  "phase",
  "phone",
  "photo",
  "phpbb",
  "piano",
  "picks",
  "piece",
  "pills",
  "pilot",
  "pipes",
  "pitch",
  "pixel",
  "pizza",
  "place",
  "plain",
  "plane",
  "plans",
  "plant",
  "plate",
  "plays",
  "plaza",
  "plots",
  "poems",
  "point",
  "poker",
  "polar",
  "polls",
  "pools",
  "ports",
  "posts",
  "pound",
  "power",
  "press",
  "price",
  "pride",
  "prime",
  "print",
  "prior",
  "prize",
  "probe",
  "promo",
  "proof",
  "proud",
  "prove",
  "proxy",
  "pulse",
  "pumps",
  "punch",
  "puppy",
  "purse",
  "qatar",
  "queen",
  "query",
  "quest",
  "queue",
  "quick",
  "quiet",
  "quilt",
  "quite",
  "quote",
  "races",
  "racks",
  "radar",
  "radio",
  "raise",
  "rally",
  "ralph",
  "ranch",
  "randy",
  "range",
  "ranks",
  "rapid",
  "rated",
  "rates",
  "ratio",
  "reach",
  "reads",
  "ready",
  "realm",
  "rebel",
  "refer",
  "rehab",
  "relax",
  "relay",
  "remix",
  "renew",
  "reply",
  "reset",
  "retro",
  "rhode",
  "ricky",
  "rider",
  "rides",
  "ridge",
  "right",
  "rings",
  "risks",
  "river",
  "roads",
  "robin",
  "robot",
  "rocks",
  "rocky",
  "roger",
  "roles",
  "rolls",
  "roman",
  "rooms",
  "roots",
  "roses",
  "rouge",
  "rough",
  "round",
  "route",
  "rover",
  "royal",
  "rugby",
  "ruled",
  "rules",
  "rural",
  "safer",
  "sagem",
  "saint",
  "salad",
  "salem",
  "sales",
  "sally",
  "salon",
  "samba",
  "samoa",
  "sandy",
  "santa",
  "sanyo",
  "sarah",
  "satin",
  "sauce",
  "saudi",
  "saved",
  "saver",
  "saves",
  "sbjct",
  "scale",
  "scary",
  "scene",
  "scoop",
  "scope",
  "score",
  "scott",
  "scout",
  "screw",
  "scuba",
  "seats",
  "seeds",
  "seeks",
  "seems",
  "sells",
  "sends",
  "sense",
  "serum",
  "serve",
  "setup",
  "seven",
  "shade",
  "shaft",
  "shake",
  "shall",
  "shame",
  "shape",
  "share",
  "shark",
  "sharp",
  "sheep",
  "sheer",
  "sheet",
  "shelf",
  "shell",
  "shift",
  "shine",
  "ships",
  "shirt",
  "shock",
  "shoes",
  "shoot",
  "shops",
  "shore",
  "short",
  "shots",
  "shown",
  "shows",
  "sides",
  "sight",
  "sigma",
  "signs",
  "silly",
  "simon",
  "since",
  "singh",
  "sites",
  "sixth",
  "sized",
  "sizes",
  "skill",
  "skins",
  "skirt",
  "skype",
  "slave",
  "sleep",
  "slide",
  "slope",
  "slots",
  "small",
  "smart",
  "smell",
  "smile",
  "smith",
  "smoke",
  "snake",
  "socks",
  "solar",
  "solid",
  "solve",
  "songs",
  "sonic",
  "sorry",
  "sorts",
  "souls",
  "sound",
  "south",
  "space",
  "spain",
  "spank",
  "sparc",
  "spare",
  "speak",
  "specs",
  "speed",
  "spell",
  "spend",
  "spent",
  "sperm",
  "spice",
  "spies",
  "spine",
  "split",
  "spoke",
  "sport",
  "spots",
  "spray",
  "squad",
  "stack",
  "staff",
  "stage",
  "stake",
  "stamp",
  "stand",
  "stars",
  "start",
  "state",
  "stats",
  "stays",
  "steal",
  "steam",
  "steel",
  "steps",
  "steve",
  "stick",
  "still",
  "stock",
  "stone",
  "stood",
  "stops",
  "store",
  "storm",
  "story",
  "strap",
  "strip",
  "stuck",
  "study",
  "stuff",
  "style",
  "sudan",
  "sugar",
  "suite",
  "suits",
  "sunny",
  "super",
  "surge",
  "susan",
  "sweet",
  "swift",
  "swing",
  "swiss",
  "sword",
  "syria",
  "table",
  "tahoe",
  "taken",
  "takes",
  "tales",
  "talks",
  "tamil",
  "tampa",
  "tanks",
  "tapes",
  "tasks",
  "taste",
  "taxes",
  "teach",
  "teams",
  "tears",
  "teddy",
  "teens",
  "teeth",
  "tells",
  "terms",
  "terry",
  "tests",
  "texas",
  "texts",
  "thank",
  "thats",
  "theft",
  "their",
  "theme",
  "there",
  "these",
  "theta",
  "thick",
  "thing",
  "think",
  "third",
  "thong",
  "those",
  "three",
  "throw",
  "thumb",
  "tiger",
  "tight",
  "tiles",
  "timer",
  "times",
  "tions",
  "tired",
  "tires",
  "title",
  "today",
  "token",
  "tokyo",
  "tommy",
  "toner",
  "tones",
  "tools",
  "tooth",
  "topic",
  "total",
  "touch",
  "tough",
  "tours",
  "tower",
  "towns",
  "toxic",
  "trace",
  "track",
  "tract",
  "tracy",
  "trade",
  "trail",
  "train",
  "trans",
  "trash",
  "treat",
  "trees",
  "trend",
  "trial",
  "tribe",
  "trick",
  "tried",
  "tries",
  "trips",
  "trout",
  "truck",
  "truly",
  "trunk",
  "trust",
  "truth",
  "tubes",
  "tulsa",
  "tumor",
  "tuner",
  "tunes",
  "turbo",
  "turns",
  "twice",
  "twiki",
  "twins",
  "twist",
  "tyler",
  "types",
  "ultra",
  "uncle",
  "under",
  "union",
  "units",
  "unity",
  "until",
  "upper",
  "upset",
  "urban",
  "usage",
  "users",
  "using",
  "usual",
  "utils",
  "valid",
  "value",
  "valve",
  "vault",
  "vegas",
  "venue",
  "verde",
  "verse",
  "video",
  "views",
  "villa",
  "vinyl",
  "viral",
  "virus",
  "visit",
  "vista",
  "vital",
  "vocal",
  "voice",
  "volvo",
  "voted",
  "votes",
  "vsnet",
  "wages",
  "wagon",
  "wales",
  "walks",
  "walls",
  "wanna",
  "wants",
  "waste",
  "watch",
  "water",
  "watts",
  "waves",
  "wayne",
  "weeks",
  "weird",
  "wells",
  "welsh",
  "wendy",
  "whale",
  "whats",
  "wheat",
  "wheel",
  "where",
  "which",
  "while",
  "white",
  "whole",
  "whose",
  "wider",
  "width",
  "wiley",
  "winds",
  "wines",
  "wings",
  "wired",
  "wires",
  "witch",
  "wives",
  "woman",
  "women",
  "woods",
  "words",
  "works",
  "world",
  "worry",
  "worse",
  "worst",
  "worth",
  "would",
  "wound",
  "wrist",
  "write",
  "wrong",
  "wrote",
  "xanax",
  "xerox",
  "xhtml",
  "yacht",
  "yahoo",
  "yards",
  "years",
  "yeast",
  "yemen",
  "yield",
  "young",
  "yours",
  "youth",
  "yukon",
  "zdnet",
  "zones",
];

var ANSWERS = [
  "about",
  "above",
  "abuse",
  "acute",
  "adopt",
  "adult",
  "after",
  "again",
  "agent",
  "agree",
  "ahead",
  "alarm",
  "album",
  "alert",
  "alien",
  "alike",
  "alive",
  "allow",
  "alone",
  "along",
  "alter",
  "amber",
  "amend",
  "among",
  "angel",
  "anger",
  "angle",
  "angry",
  "apart",
  "apple",
  "apply",
  "april",
  "arena",
  "argue",
  "arise",
  "armed",
  "armor",
  "array",
  "arrow",
  "aside",
  "asked",
  "asset",
  "audio",
  "audit",
  "avoid",
  "award",
  "aware",
  "awful",
  "bacon",
  "badge",
  "badly",
  "baker",
  "basic",
  "basin",
  "basis",
  "batch",
  "beach",
  "beads",
  "beans",
  "bears",
  "beast",
  "beats",
  "began",
  "begin",
  "begun",
  "being",
  "belly",
  "below",
  "bench",
  "berry",
  "bible",
  "bikes",
  "bills",
  "birth",
  "black",
  "blade",
  "blame",
  "blank",
  "blast",
  "blend",
  "bless",
  "blind",
  "blink",
  "block",
  "blood",
  "bloom",
  "blues",
  "board",
  "boats",
  "bones",
  "bonus",
  "books",
  "boost",
  "booth",
  "boots",
  "bored",
  "bound",
  "brain",
  "brake",
  "brand",
  "brass",
  "brave",
  "bread",
  "break",
  "breed",
  "brick",
  "bride",
  "brief",
  "bring",
  "broad",
  "broke",
  "brook",
  "brown",
  "brush",
  "build",
  "built",
  "bunch",
  "bunny",
  "burns",
  "burst",
  "buyer",
  "cabin",
  "cable",
  "cakes",
  "calls",
  "camel",
  "camps",
  "canal",
  "candy",
  "cards",
  "cargo",
  "carry",
  "cases",
  "catch",
  "cause",
  "cells",
  "cents",
  "chain",
  "chair",
  "chaos",
  "charm",
  "chart",
  "chase",
  "cheap",
  "cheat",
  "check",
  "chess",
  "chest",
  "chick",
  "chief",
  "child",
  "chips",
  "choir",
  "chose",
  "civic",
  "civil",
  "claim",
  "class",
  "clean",
  "clear",
  "clerk",
  "click",
  "cliff",
  "climb",
  "clock",
  "clone",
  "close",
  "cloth",
  "cloud",
  "clubs",
  "coach",
  "coast",
  "codes",
  "coins",
  "color",
  "combo",
  "comes",
  "comic",
  "coral",
  "could",
  "count",
  "court",
  "cover",
  "crack",
  "craft",
  "crash",
  "crazy",
  "cream",
  "creek",
  "crest",
  "crime",
  "crops",
  "cross",
  "crowd",
  "crown",
  "crude",
  "curve",
  "cycle",
  "daily",
  "dairy",
  "dance",
  "dates",
  "death",
  "debut",
  "delay",
  "delta",
  "dense",
  "depth",
  "devil",
  "diary",
  "dirty",
  "disco",
  "doing",
  "donor",
  "doors",
  "doubt",
  "dozen",
  "draft",
  "drain",
  "drama",
  "dream",
  "dress",
  "dried",
  "drill",
  "drink",
  "drive",
  "drops",
  "drove",
  "drugs",
  "drums",
  "drunk",
  "early",
  "earth",
  "eight",
  "elder",
  "elect",
  "elite",
  "email",
  "empty",
  "enemy",
  "enjoy",
  "enter",
  "entry",
  "equal",
  "error",
  "essay",
  "event",
  "every",
  "exact",
  "exams",
  "exist",
  "extra",
  "faced",
  "faces",
  "facts",
  "fails",
  "faith",
  "falls",
  "false",
  "fancy",
  "farms",
  "fatal",
  "fault",
  "favor",
  "fears",
  "feeds",
  "feels",
  "fence",
  "ferry",
  "fever",
  "fewer",
  "fiber",
  "field",
  "fifth",
  "fifty",
  "fight",
  "filed",
  "files",
  "films",
  "final",
  "finds",
  "fired",
  "fires",
  "firms",
  "first",
  "fixed",
  "flags",
  "flame",
  "flash",
  "fleet",
  "flesh",
  "float",
  "flood",
  "floor",
  "flour",
  "flows",
  "fluid",
  "flush",
  "focal",
  "focus",
  "folks",
  "fonts",
  "foods",
  "force",
  "forge",
  "forms",
  "forth",
  "forty",
  "forum",
  "found",
  "frame",
  "fraud",
  "fresh",
  "front",
  "frost",
  "fruit",
  "fully",
  "funds",
  "funny",
  "fuzzy",
  "games",
  "gates",
  "gauge",
  "genre",
  "ghost",
  "giant",
  "gifts",
  "girls",
  "given",
  "gives",
  "glass",
  "globe",
  "glory",
  "goals",
  "going",
  "goods",
  "grace",
  "grade",
  "grain",
  "grand",
  "grant",
  "graph",
  "grass",
  "grave",
  "great",
  "green",
  "grill",
  "gross",
  "group",
  "grove",
  "grown",
  "grows",
  "guard",
  "guess",
  "guest",
  "guide",
  "hands",
  "handy",
  "happy",
  "heavy",
  "hello",
  "helps",
  "hence",
  "honor",
  "hoped",
  "hopes",
  "horse",
  "hotel",
  "hours",
  "house",
  "human",
  "humor",
  "ideal",
  "ideas",
  "image",
  "index",
  "inner",
  "input",
  "issue",
  "items",
  "ivory",
  "jeans",
  "jewel",
  "judge",
  "juice",
  "keeps",
  "kinds",
  "knife",
  "knock",
  "known",
  "knows",
  "label",
  "labor",
  "lakes",
  "large",
  "laser",
  "later",
  "laugh",
  "layer",
  "leads",
  "learn",
  "lease",
  "least",
  "leave",
  "legal",
  "lemon",
  "level",
  "light",
  "liked",
  "likes",
  "limit",
  "lined",
  "lines",
  "links",
  "lists",
  "lived",
  "liver",
  "lives",
  "local",
  "locks",
  "lodge",
  "logic",
  "login",
  "looks",
  "loops",
  "loose",
  "lover",
  "loves",
  "lower",
  "lucky",
  "lunch",
  "lying",
  "lyric",
  "magic",
  "major",
  "maker",
  "makes",
  "males",
  "manor",
  "maple",
  "march",
  "match",
  "maybe",
  "mayor",
  "meals",
  "means",
  "meant",
  "medal",
  "media",
  "meets",
  "mercy",
  "merge",
  "merit",
  "merry",
  "metal",
  "meter",
  "might",
  "miles",
  "minds",
  "mines",
  "minor",
  "minus",
  "mixed",
  "mixer",
  "model",
  "money",
  "month",
  "moral",
  "motel",
  "motor",
  "mount",
  "mouse",
  "mouth",
  "moved",
  "moves",
  "movie",
  "music",
  "nails",
  "naked",
  "named",
  "names",
  "nasty",
  "naval",
  "needs",
  "nerve",
  "never",
  "newer",
  "newly",
  "night",
  "noble",
  "nodes",
  "noise",
  "north",
  "noted",
  "notes",
  "novel",
  "nurse",
  "nylon",
  "oasis",
  "occur",
  "ocean",
  "offer",
  "often",
  "older",
  "olive",
  "omega",
  "onion",
  "opens",
  "opera",
  "orbit",
  "order",
  "organ",
  "other",
  "ought",
  "outer",
  "owned",
  "owner",
  "oxide",
  "ozone",
  "packs",
  "pages",
  "paint",
  "pairs",
  "panel",
  "panic",
  "pants",
  "paper",
  "parks",
  "parts",
  "party",
  "pasta",
  "paste",
  "patch",
  "paths",
  "patio",
  "peace",
  "pearl",
  "peers",
  "penny",
  "phase",
  "phone",
  "photo",
  "piano",
  "picks",
  "piece",
  "pills",
  "pilot",
  "pipes",
  "pitch",
  "pixel",
  "pizza",
  "place",
  "plain",
  "plane",
  "plans",
  "plant",
  "plate",
  "plays",
  "plaza",
  "plots",
  "poems",
  "point",
  "poker",
  "polar",
  "polls",
  "pools",
  "ports",
  "posts",
  "pound",
  "power",
  "press",
  "price",
  "pride",
  "prime",
  "print",
  "prior",
  "prize",
  "probe",
  "promo",
  "proof",
  "proud",
  "prove",
  "proxy",
  "pulse",
  "pumps",
  "punch",
  "puppy",
  "purse",
  "queen",
  "query",
  "quest",
  "queue",
  "quick",
  "quiet",
  "quilt",
  "quite",
  "quote",
  "races",
  "racks",
  "radar",
  "radio",
  "raise",
  "rally",
  "ranch",
  "range",
  "ranks",
  "rapid",
  "rated",
  "rates",
  "ratio",
  "reach",
  "reads",
  "ready",
  "realm",
  "rebel",
  "refer",
  "relax",
  "relay",
  "renew",
  "reply",
  "reset",
  "retro",
  "rider",
  "rides",
  "ridge",
  "right",
  "rings",
  "risks",
  "river",
  "roads",
  "robin",
  "robot",
  "rocks",
  "rocky",
  "roles",
  "rolls",
  "roman",
  "rooms",
  "roots",
  "roses",
  "rough",
  "round",
  "route",
  "rover",
  "royal",
  "rugby",
  "ruled",
  "rules",
  "rural",
  "safer",
  "saint",
  "salad",
  "sales",
  "sandy",
  "sauce",
  "saved",
  "saver",
  "saves",
  "scale",
  "scary",
  "scene",
  "scoop",
  "scope",
  "score",
  "scout",
  "screw",
  "seats",
  "seeds",
  "seeks",
  "seems",
  "sells",
  "sends",
  "sense",
  "serve",
  "setup",
  "seven",
  "shade",
  "shaft",
  "shake",
  "shall",
  "shame",
  "shape",
  "share",
  "shark",
  "sharp",
  "sheep",
  "sheer",
  "sheet",
  "shelf",
  "shell",
  "shift",
  "shine",
  "ships",
  "shirt",
  "shock",
  "shoes",
  "shoot",
  "shops",
  "shore",
  "short",
  "shots",
  "shown",
  "shows",
  "sides",
  "sight",
  "signs",
  "silly",
  "since",
  "sites",
  "sixth",
  "sized",
  "sizes",
  "skill",
  "skins",
  "skirt",
  "slave",
  "sleep",
  "slide",
  "slope",
  "slots",
  "small",
  "smart",
  "smell",
  "smile",
  "smoke",
  "snake",
  "socks",
  "solar",
  "solid",
  "solve",
  "songs",
  "sonic",
  "sorry",
  "sorts",
  "souls",
  "sound",
  "south",
  "space",
  "spare",
  "speak",
  "specs",
  "speed",
  "spell",
  "spend",
  "spent",
  "spice",
  "spies",
  "spine",
  "split",
  "spoke",
  "sport",
  "spots",
  "spray",
  "squad",
  "stack",
  "staff",
  "stage",
  "stake",
  "stamp",
  "stand",
  "stars",
  "start",
  "state",
  "stays",
  "steal",
  "steam",
  "steel",
  "steps",
  "stick",
  "still",
  "stock",
  "stone",
  "stood",
  "stops",
  "store",
  "storm",
  "story",
  "strap",
  "strip",
  "stuck",
  "study",
  "stuff",
  "style",
  "sugar",
  "suite",
  "suits",
  "sunny",
  "super",
  "surge",
  "sweet",
  "swift",
  "swing",
  "sword",
  "table",
  "taken",
  "takes",
  "tales",
  "talks",
  "tanks",
  "tapes",
  "tasks",
  "taste",
  "taxes",
  "teach",
  "teams",
  "tears",
  "teens",
  "teeth",
  "tells",
  "terms",
  "tests",
  "texts",
  "thank",
  "theft",
  "their",
  "theme",
  "there",
  "these",
  "thick",
  "thing",
  "think",
  "third",
  "those",
  "three",
  "throw",
  "thumb",
  "tiger",
  "tight",
  "tiles",
  "timer",
  "times",
  "tired",
  "tires",
  "title",
  "today",
  "token",
  "tones",
  "tools",
  "tooth",
  "topic",
  "total",
  "touch",
  "tough",
  "tours",
  "tower",
  "towns",
  "toxic",
  "trace",
  "track",
  "trade",
  "trail",
  "train",
  "trash",
  "treat",
  "trees",
  "trend",
  "trial",
  "tribe",
  "trick",
  "tried",
  "tries",
  "trips",
  "trout",
  "truck",
  "truly",
  "trunk",
  "trust",
  "truth",
  "tubes",
  "tumor",
  "tunes",
  "turbo",
  "turns",
  "twice",
  "twins",
  "twist",
  "types",
  "ultra",
  "uncle",
  "under",
  "union",
  "units",
  "unity",
  "until",
  "upper",
  "upset",
  "urban",
  "usage",
  "users",
  "using",
  "usual",
  "valid",
  "value",
  "valve",
  "vault",
  "venue",
  "verse",
  "video",
  "views",
  "villa",
  "vinyl",
  "viral",
  "virus",
  "visit",
  "vista",
  "vital",
  "vocal",
  "voice",
  "voted",
  "votes",
  "wages",
  "wagon",
  "walks",
  "walls",
  "wants",
  "waste",
  "watch",
  "water",
  "waves",
  "weeks",
  "weird",
  "wells",
  "whale",
  "wheat",
  "wheel",
  "where",
  "which",
  "while",
  "white",
  "whole",
  "whose",
  "wider",
  "width",
  "winds",
  "wines",
  "wings",
  "wired",
  "wires",
  "witch",
  "wives",
  "woman",
  "women",
  "woods",
  "words",
  "works",
  "world",
  "worry",
  "worse",
  "worst",
  "worth",
  "would",
  "wound",
  "wrist",
  "write",
  "wrong",
  "wrote",
  "yacht",
  "yards",
  "years",
  "yeast",
  "yield",
  "young",
  "yours",
  "youth",
  "zones",
];


  var GUESSES = new Set(DICT);
  var ANSWERS_SET = new Set(ANSWERS);

  var MAX_GUESSES = 6;
  var WORD_LEN = 5;

  var STORE_KEY = "wordle_stats";
  var saved = loadSaved();

  var boardEl = document.getElementById("board");
  var keyboardEl = document.getElementById("keyboard");
  var messageEl = document.getElementById("message");
  var overlay = document.getElementById("overlay");
  var panelTitle = document.getElementById("panelTitle");
  var panelAnswer = document.getElementById("panelAnswer");
  var panelShare = document.getElementById("panelShare");
  var copyStatus = document.getElementById("copyStatus");
  var shareBtn = document.getElementById("shareBtn");
  var newBtn = document.getElementById("newBtn");
  var restartBtn = document.getElementById("restartBtn");

  var answer = "";
  var guesses = [];        // array of submitted words (strings)
  var current = "";        // letters typed but not yet submitted
  var over = false;
  var won = false;
  var busy = false;        // lock during reveal animation

  var rows = [];           // rows[r] = array of tile elements
  var keys = {};           // letter -> key button element
  var keyState = {};       // letter -> "green" | "yellow" | "gray" | ""

  var KEY_ROWS = [
    ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p"],
    ["a", "s", "d", "f", "g", "h", "j", "k", "l"],
    ["ENTER", "z", "x", "c", "v", "b", "n", "m", "DEL"]
  ];

  /* ------------------------------------------------------------------ */
  /* persistence                                                       */
  /* ------------------------------------------------------------------ */

  function loadSaved() {
    var s = null;
    try {
      s = JSON.parse(localStorage.getItem(STORE_KEY) || "{}");
    } catch (e) {
      s = {};
    }
    if (!s || typeof s !== "object") s = {};
    if (typeof s.games !== "number") s.games = 0;
    if (typeof s.wins !== "number") s.wins = 0;
    if (typeof s.streak !== "number") s.streak = 0;
    if (typeof s.best !== "number") s.best = 0;
    return s;
  }

  function saveSaved() {
    try {
      localStorage.setItem(STORE_KEY, JSON.stringify(saved));
    } catch (e) { /* ignore */ }
  }

  /* ------------------------------------------------------------------ */
  /* board + keyboard rendering                                         */
  /* ------------------------------------------------------------------ */

  function buildBoard() {
    boardEl.innerHTML = "";
    rows = [];
    for (var r = 0; r < MAX_GUESSES; r++) {
      var rowEl = document.createElement("div");
      rowEl.className = "board";
      rowEl.style.display = "contents";
      var row = [];
      for (var c = 0; c < WORD_LEN; c++) {
        var tile = document.createElement("div");
        tile.className = "tile";
        tile.setAttribute("data-r", r);
        tile.setAttribute("data-c", c);
        rowEl.appendChild(tile);
        row.push(tile);
      }
      boardEl.appendChild(rowEl);
      rows.push(row);
    }
  }

  function buildKeyboard() {
    keyboardEl.innerHTML = "";
    keys = {};
    keyState = {};
    KEY_ROWS.forEach(function (rowLetters, idx) {
      var row = document.createElement("div");
      row.className = "keyrow";
      rowLetters.forEach(function (letter) {
        var btn = document.createElement("button");
        btn.type = "button";
        btn.className = "key";
        if (letter === "ENTER" || letter === "DEL") btn.classList.add("wide");
        btn.textContent = letter === "DEL" ? "\u232b" : letter;
        btn.addEventListener("click", function () {
          pressKey(letter);
        });
        row.appendChild(btn);
        if (letter !== "ENTER" && letter !== "DEL") {
          keys[letter] = btn;
          keyState[letter] = "";
        }
      });
      keyboardEl.appendChild(row);
    });
  }

  /* ------------------------------------------------------------------ */
  /* game flow                                                          */
  /* ------------------------------------------------------------------ */

  function newGame() {
    // pick a random word from the answer pool
    answer = ANSWERS[Math.floor(Math.random() * ANSWERS.length)];
    guesses = [];
    current = "";
    over = false;
    won = false;
    busy = false;
    messageEl.textContent = "\u00a0";
    messageEl.className = "message";
    overlay.classList.add("hidden");
    buildBoard();
    buildKeyboard();
    render();
  }

  function render() {
    for (var r = 0; r < MAX_GUESSES; r++) {
      var word = r < guesses.length ? guesses[r] : (r === guesses.length ? current : "");
      for (var c = 0; c < WORD_LEN; c++) {
        var tile = rows[r][c];
        var ch = word.charAt(c) || "";
        tile.textContent = ch;
        tile.className = "tile" + (ch ? " filled" : "");
        // keep reveal classes only for submitted rows
        if (r < guesses.length) {
          tile.classList.add("reveal");
          tile.classList.add(evalRow(guesses[r])[c]);
        }
      }
    }
  }

  /* ------------------------------------------------------------------ */
  /* evaluation                                                         */
  /* ------------------------------------------------------------------ */

  // Standard Wordle duplicate-letter rules: green first, then yellow for
  // remaining letters, leftover letters are gray.
  function evalRow(word) {
    var status = ["gray", "gray", "gray", "gray", "gray"];
    var used = [false, false, false, false, false];
    var i, j;
    for (i = 0; i < WORD_LEN; i++) {
      if (word.charAt(i) === answer.charAt(i)) {
        status[i] = "green";
        used[i] = true;
      }
    }
    for (i = 0; i < WORD_LEN; i++) {
      if (status[i] === "green") continue;
      for (j = 0; j < WORD_LEN; j++) {
        if (!used[j] && word.charAt(i) === answer.charAt(j)) {
          status[i] = "yellow";
          used[j] = true;
          break;
        }
      }
    }
    return status;
  }

  /* ------------------------------------------------------------------ */
  /* input handling                                                     */
  /* ------------------------------------------------------------------ */

  function typeLetter(ch) {
    if (over || busy) return;
    if (current.length >= WORD_LEN) return;
    current += ch;
    messageEl.textContent = "\u00a0";
    messageEl.className = "message";
    render();
  }

  function backspace() {
    if (over || busy) return;
    if (current.length === 0) return;
    current = current.slice(0, -1);
    render();
  }

  function submit() {
    if (over || busy) return;
    if (current.length < WORD_LEN) {
      showMessage("Not enough letters", true);
      return;
    }
    var word = current;
    if (!GUESSES.has(word)) {
      showMessage("Not in word list", true);
      return;
    }
    current = "";
    busy = true;
    var r = guesses.length;
    guesses.push(word);
    var status = evalRow(word);

    // update keyboard states (best state wins: green > yellow > gray)
    for (var i = 0; i < WORD_LEN; i++) {
      var ch = word.charAt(i);
      var st = status[i];
      var cur = keyState[ch];
      if (st === "green") keyState[ch] = "green";
      else if (st === "yellow" && cur !== "green") keyState[ch] = "yellow";
      else if (!cur) keyState[ch] = "gray";
    }
    applyKeyStates();

    // reveal animation
    var delay = 0;
    for (var k = 0; k < WORD_LEN; k++) {
      (function (col, st) {
        setTimeout(function () {
          var tile = rows[r][col];
          tile.textContent = word.charAt(col);
          tile.className = "tile reveal " + st;
        }, delay);
        delay += 240;
      })(k, status[k]);
    }
    setTimeout(function () {
      busy = false;
      if (word === answer) {
        finish(true);
      } else if (r === MAX_GUESSES - 1) {
        finish(false);
      }
    }, delay + 300);
  }

  function applyKeyStates() {
    Object.keys(keys).forEach(function (ch) {
      var st = keyState[ch] || "";
      keys[ch].className = "key" + (st ? " " + st : "");
    });
  }

  function pressKey(k) {
    if (k === "ENTER") submit();
    else if (k === "DEL") backspace();
    else typeLetter(k.toLowerCase());
  }

  /* ------------------------------------------------------------------ */
  /* end of game                                                        */
  /* ------------------------------------------------------------------ */

  function finish(w) {
    over = true;
    won = w;
    saved.games++;
    if (w) {
      saved.wins++;
      saved.streak++;
      if (saved.streak > saved.best) saved.best = saved.streak;
    } else {
      saved.streak = 0;
    }
    saveSaved();

    // win animation on the answer row
    if (w) {
      var row = rows[guesses.length - 1];
      for (var i = 0; i < WORD_LEN; i++) {
        (function (tile, idx) {
          setTimeout(function () {
            tile.classList.add("winpop");
          }, idx * 90);
        })(row[i], i);
      }
    }

    setTimeout(function () {
      showResult(w);
    }, w ? 600 : 500);
  }

  function showResult(w) {
    panelTitle.textContent = w ? "You got it!" : "Out of guesses";
    var ans = answer.toUpperCase();
    panelAnswer.innerHTML = "The word was <b>" + ans + "</b>";
    panelShare.textContent = buildShareText();
    copyStatus.textContent = "\u00a0";
    overlay.classList.remove("hidden");
  }

  function buildShareText() {
    var lines = [];
    for (var r = 0; r < guesses.length; r++) {
      var status = evalRow(guesses[r]);
      var line = "";
      for (var c = 0; c < WORD_LEN; c++) {
        line += status[c] === "green" ? "\ud83d\udfe9" :
                status[c] === "yellow" ? "\ud83d\udfe8" : "\u2b1b";
      }
      lines.push(line);
    }
    if (!won) lines.push("\u2b1b\u2b1b\u2b1b\u2b1b\u2b1b");
    var tries = won ? guesses.length + "/6" : "X/6";
    return "Wordle " + tries + "\n" + lines.join("\n");
  }

  function copyShare() {
    var text = buildShareText();
    var done = function () {
      copyStatus.textContent = "\u2713 Copied";
    };
    var fail = function () {
      copyStatus.textContent = "\u2718 Could not copy \u2014 select the grid above and copy manually";
    };
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).then(done, function () {
        legacyCopy(text, done, fail);
      });
    } else {
      legacyCopy(text, done, fail);
    }
  }

  // Fallback for browsers without the async Clipboard API.
  function legacyCopy(text, done, fail) {
    var ta = document.createElement("textarea");
    ta.value = text;
    ta.setAttribute("readonly", "");
    ta.style.position = "fixed";
    ta.style.top = "0";
    ta.style.left = "0";
    ta.style.opacity = "0";
    document.body.appendChild(ta);
    ta.select();
    ta.setSelectionRange(0, text.length);
    var ok = false;
    try {
      ok = document.execCommand("copy");
    } catch (e) {
      ok = false;
    }
    document.body.removeChild(ta);
    if (ok) done();
    else fail();
  }

  /* ------------------------------------------------------------------ */
  /* helpers                                                            */
  /* ------------------------------------------------------------------ */

  function showMessage(text, bad) {
    messageEl.textContent = text;
    messageEl.className = "message" + (bad ? " error" : " ok");
  }

  /* ------------------------------------------------------------------ */
  /* events                                                             */
  /* ------------------------------------------------------------------ */

  window.addEventListener("keydown", function (e) {
    if (e.ctrlKey || e.metaKey || e.altKey) return;
    if (e.code === "Enter") {
      e.preventDefault();
      submit();
      return;
    }
    if (e.code === "Backspace") {
      e.preventDefault();
      backspace();
      return;
    }
    if (e.code === "KeyR") {
      e.preventDefault();
      newGame();
      return;
    }
    var ch = e.key;
    if (ch && ch.length === 1 && /[a-zA-Z]/.test(ch)) {
      e.preventDefault();
      typeLetter(ch.toLowerCase());
    }
  });

  restartBtn.addEventListener("click", newGame);
  newBtn.addEventListener("click", newGame);
  shareBtn.addEventListener("click", copyShare);

  newGame();
})();
